# Generated by Django 4.0.4 on 2022-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_remove_employee_address_remove_employee_approvedvac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
