# Generated by Django 4.0.4 on 2022-05-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_alter_log_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='log',
        ),
    ]
