# Generated by Django 4.0.4 on 2022-05-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log',
        ),
    ]
