# Generated by Django 4.0.4 on 2022-05-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_alter_employee_gender_alter_employee_maritalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacStart', models.DateField()),
                ('vacEnd', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.employee')),
            ],
        ),
    ]
