# Generated by Django 4.0.4 on 2022-05-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0010_vacations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacations',
            old_name='ID',
            new_name='employee',
        ),
    ]
