# Generated by Django 4.0.4 on 2022-05-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0012_remove_vacations_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.employee'),
        ),
    ]
