# Generated by Django 4.0.4 on 2022-05-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0013_vacations_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ID',
            new_name='IDR',
        ),
    ]
