# Generated by Django 4.0.4 on 2022-05-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0014_rename_id_employee_idr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='IDR',
            new_name='ID',
        ),
    ]
