# Generated by Django 4.0.4 on 2022-05-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0016_importantmeetings_officialholidays_trainings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialholidays',
            name='available',
        ),
        migrations.AddField(
            model_name='importantmeetings',
            name='MeetingID',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='officialholidays',
            name='coming_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='officialholidays',
            name='name',
            field=models.CharField(default='Official Holiday', max_length=60),
        ),
        migrations.AddField(
            model_name='officialholidays',
            name='planned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainings',
            name='name',
            field=models.CharField(default='Training', max_length=60),
        ),
        migrations.AlterField(
            model_name='importantmeetings',
            name='declared',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='importantmeetings',
            name='planned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='importantmeetings',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officialholidays',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trainings',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
