# Generated by Django 4.0.4 on 2022-05-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0017_remove_officialholidays_available_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='importantMeetings',
            new_name='importantMeeting',
        ),
        migrations.RenameModel(
            old_name='OfficialHolidays',
            new_name='OfficialHoliday',
        ),
        migrations.RenameModel(
            old_name='Trainings',
            new_name='Training',
        ),
        migrations.RenameModel(
            old_name='Vacations',
            new_name='Vacation',
        ),
    ]
