# Generated by Django 4.0.4 on 2022-05-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0018_rename_importantmeetings_importantmeeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
