# Generated by Django 4.0.4 on 2022-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0019_vacation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vacEnd',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vacStart',
            field=models.DateField(null=True),
        ),
    ]
