# Generated by Django 4.0.4 on 2022-05-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0022_alter_employee_gender_alter_employee_maritalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='maritalstatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=7),
        ),
    ]
